name: routine_quest_client
description: Routine Quest App - Flutter 클라이언트
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management - Git 의존성 제거 버전
  flutter_riverpod: ^2.4.0

  # Routing
  go_router: ^12.0.0

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # HTTP Client
  http: ^1.1.0

  # UI
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
